// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQCkCvGtvNbopA-eYlVsZQlT_ILxvTsI8',
    appId: '1:799628710184:web:ad4960a76af216e1c1801d',
    messagingSenderId: '799628710184',
    projectId: 'thandriusers',
    authDomain: 'thandriusers.firebaseapp.com',
    storageBucket: 'thandriusers.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-ya96B9F0o_6b6FFWE9IHlbgzg4yLako',
    appId: '1:799628710184:android:d0186b692879f71dc1801d',
    messagingSenderId: '799628710184',
    projectId: 'thandriusers',
    storageBucket: 'thandriusers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFcIEBijQhsnG_eIRo5BxmWBsoQAGXJeg',
    appId: '1:799628710184:ios:110eb2e443373804c1801d',
    messagingSenderId: '799628710184',
    projectId: 'thandriusers',
    storageBucket: 'thandriusers.appspot.com',
    iosBundleId: 'com.example.thandriSannidhi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFcIEBijQhsnG_eIRo5BxmWBsoQAGXJeg',
    appId: '1:799628710184:ios:83ce7eb9f59bc4e9c1801d',
    messagingSenderId: '799628710184',
    projectId: 'thandriusers',
    storageBucket: 'thandriusers.appspot.com',
    iosBundleId: 'com.example.thandriSannidhi.RunnerTests',
  );
}
