class Mp3Songs {
  String name;
  String album;
  String link;
  Mp3Songs(this.name, this.album, this.link);
}

List mp3songs = [
//      1    //

  Mp3Songs("అదిగో ప్రియుని కేక", "సత్య స్వరూపుడా నా యేసయ్య",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/2-ADHIGO-PRIYUNI-KEKA-WAV.mp3'),
  Mp3Songs("వెండి బంగారములు", "సత్య స్వరూపుడా నా యేసయ్య",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/4-VENDI-BANGARALU.mp3'),
  Mp3Songs("రాజువైన నా దేవా", "సత్య స్వరూపుడా నా యేసయ్య",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/5-RAJUVINA-NA-DEVA-WAV.mp3'),
  Mp3Songs("యేసు రక్తమే", "సత్య స్వరూపుడా నా యేసయ్య",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/6-yesu-rakthame-song.mp3'),
  Mp3Songs("ప్రేమకే స్వాగతం", "సత్య స్వరూపుడా నా యేసయ్య",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/3-PREMAKY-SWAGATHAM.mp3'),
  Mp3Songs("నా నీతికి ఆధారమా", "సత్య స్వరూపుడా నా యేసయ్య",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/1-NA-NITHIKI-ADHARAMA-WAV.mp3'),
  Mp3Songs("కావాలి కావాలి", "సత్య స్వరూపుడా నా యేసయ్య",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/7-KAAVALI-KAAVALI-WAV.mp3'),
  Mp3Songs("సర్వ శక్తిగల దేవా", "సత్య స్వరూపుడా నా యేసయ్య",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/8-SARVA-SHAKTHI-GALA-DEVA.mp3'),

//      2    //

  Mp3Songs("సర్వభూమికి రాజైన దేవా", "యేసే సర్వశక్తుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/SARVA-BHOMIKI-MIX-22-02-22-VER-04.mp3'),
  Mp3Songs("నా గురి నీవే నా దరి నీవే", "యేసే సర్వశక్తుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/%E0%B0%A8%E0%B0%BE-%E0%B0%97%E0%B1%81%E0%B0%B0%E0%B0%BF-%E0%B0%A8%E0%B1%80%E0%B0%B5%E0%B1%87-%E0%B0%A8%E0%B0%BE-%E0%B0%A6%E0%B0%B0%E0%B0%BF-%E0%B0%A8%E0%B1%80%E0%B0%B5%E0%B1%87-13-VOL-%E0%B0%AF%E0%B1%87%E0%B0%B8%E0%B1%87-%E0%B0%B8%E0%B0%B0%E0%B1%8D%E0%B0%B5%E0%B0%B6%E0%B0%95%E0%B1%8D%E0%B0%A4%E0%B1%81%E0%B0%A1%E0%B1%81-2022-NEW-SONG-BY-BRO.SHALEM-RAJU-GARUMP3_128K.mp3'),
  Mp3Songs("ఎంత చిత్రమో.... ", "యేసే సర్వశక్తుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/%E0%B0%8F%E0%B0%82%E0%B0%A4-%E0%B0%9A%E0%B0%BF%E0%B0%A4%E0%B1%8D%E0%B0%B0%E0%B0%AE%E0%B1%8B-%E0%B0%8F%E0%B0%AE%E0%B0%BF-%E0%B0%9A%E0%B1%8B%E0%B0%A6%E0%B1%8D%E0%B0%AF%E0%B0%AE%E0%B1%8B-NEW-CHRISTMAS-SONG-BY-BRO-SHALEM-RAJU-ANNA.mp3'),
  Mp3Songs("నీ దుఃఖ దినములు", "యేసే సర్వశక్తుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/Ne-Dhukka-Dinamulu-Final-Master.mp3'),

  //      3    //

  Mp3Songs("నిన్నే తలచి - నిన్నే వలచి", "నీ కృప",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/1-HRUDAYAMA-FINAL-1.mp3'),
  Mp3Songs(" హల్లెలూయా - హల్లెలూయా", "నీ కృప",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/4-KURIPINCHIMU-FINAL-1.mp3'),
  Mp3Songs(" ప్రభువా హితవత్సరం", "నీ కృప",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/PRBHUVA-FINAL.wav'),
  Mp3Songs("నీ కృప బాహుళ్యమే", "స్నీ కృప",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/5-NEE-KRUPA-FINAL.mp3'),
  Mp3Songs(" దేవా.... దేవా....", "నీ కృప",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/2-DEVA-NEW-FINAL.mp3'),

  //      4    //

  Mp3Songs(" ఎబినేజర ఎబినేజర ", "స్తోత్ర నిది",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/01.Ebinezare.mp3'),
  Mp3Songs(" నీవు లేకపోతే", "స్తోత్ర నిది",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/05.Neevu-Lekapothey.mp3'),
  Mp3Songs("లెమ్ము తేజరిల్లుము నీవు", "స్తోత్ర నిది",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/03.Lemmu_.mp3'),
  Mp3Songs("శ్రమ దినమున నీవు కృంగితే", "స్తోత్ర నిది",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/07.Sramadhin.mp3'),
  Mp3Songs("యేసయ్యా నా దేవా", "స్తోత్ర నిది",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/04.Yessyya-Naa-Deva.mp3'),
  Mp3Songs(" అడుగమంటివే", "స్తోత్ర నిది",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/06.Adagamantive.mp3'),
  Mp3Songs("విరిగి నలిగిన మనస్సు", "స్తోత్ర నిది",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/08.Virigina.mp3'),
  Mp3Songs(" వేనోళ్ళ కొనియాడిన", "స్తోత్ర నిది",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/02.Velonna-02.mp3'),
  Mp3Songs("స్తుతి గీతమే పాడనా ", "స్తోత్ర నిది",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/STUTHIGEETHAMAY-FINAL.mp3'),

  //      5    //

  Mp3Songs(" దేవా దర్శించు మా దేశం", "యేసే నీతి సూర్యుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/02.DEVA-DARSINCHU.mp3'),
  Mp3Songs(" ఆశ్రయమే నీ రక్తమే", "యేసే నీతి సూర్యుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/03.AASRAYAME.mp3'),
  Mp3Songs("ప్రేమా స్వరూపుడా", "యేసే నీతి సూర్యుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/04.PREMA-SWARUPUDA.mp3'),
  Mp3Songs(" ఆలోచించరదేలా", "యేసే నీతి సూర్యుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/05.ALOCHINCHARA.mp3'),
  Mp3Songs("సింహాసనాసీనుడు", "యేసే నీతి సూర్యుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/06.SIMHAASANAA.mp3'),
  Mp3Songs(" దేవుని ప్రేమించువారికి", "యేసే నీతి సూర్యుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/07.DEVUNIPREMINCHUVAARIKI.mp3'),
  Mp3Songs("ప్రభువా నీ సన్నిధిలో", "యేసే నీతి సూర్యుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/08.THANDRI.mp3'),
  Mp3Songs("నన్ను బలపరచువానియందే", "యేసే నీతి సూర్యుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/09.NANNU-BALAPARACHU.mp3'),
  Mp3Songs("ఆత్మీయుడా నీ అనురాగము", "యేసే నీతి సూర్యుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/02-ATMIYUDA-2.mp3'),

//      6    //

  Mp3Songs(" జగతి పునాదులు", "యేసే ఆది సంభూతుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/02-JAGATHI-final.mp3'),
  Mp3Songs(" ఆకాశమందు నీవు తప్ప", "యేసే ఆది సంభూతుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/03-FINAL-AKASHAMANDU.mp3'),
  Mp3Songs("ఊహించలేదయ్యా ఈ జీవితం", "యేసే ఆది సంభూతుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/04-OOHINCHALENU-FINAL.mp3'),
  Mp3Songs(" నిన్నే స్తుతియింతును", "యేసే ఆది సంభూతుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/05-FINAL-YESAIAH.mp3'),
  Mp3Songs("గుర్తుచేసుకో మనసా", "యేసే ఆది సంభూతుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/06-GURTHU-CHESUKO-FINAL-GURTHU-CHESUKO-FINAL.mp3'),
  Mp3Songs(" మహాదేవుడా", "యేసే ఆది సంభూతుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/07-MAHA-DEVUDA-FINAL-MAHA-DEVUDA-FINAL.mp3'),
  Mp3Songs("దేవా నా దేవుడవు నీవేనని", "యేసే ఆది సంభూతుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/10-DEVA-NAA-FINAL.mp3'),
  Mp3Songs("సహోదరులు ఐక్యత కలిగి", "యేసే ఆది సంభూతుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/09-FINAL-SAHODARULU.mp3'),
  Mp3Songs("సమాప్తమాయెను", "యేసే ఆది సంభూతుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/Samapthamayenu.mp3'),

//      7    //

  Mp3Songs(" నా స్తోత్ర గానమా", "యేసే నా ప్రాణ దీపం",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/02-NA-STOTHRA.mp3'),
  Mp3Songs(" గతకాలమంత", "యేసే నా ప్రాణ దీపం",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/03-GATHAKALA.mp3'),
  Mp3Songs("అనుకున్నావా", "యేసే నా ప్రాణ దీపం",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/04-ANUKUNNAVA.mp3'),
  Mp3Songs("నినుగాచువాడు నరుడు కాడు", "యేసే నా ప్రాణ దీపం",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/05-NINU-KACHUVADU.mp3'),
  Mp3Songs("నీతోనే అనుబంధం", "యేసే నా ప్రాణ దీపం",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/06-NEETHONE.mp3'),
  Mp3Songs("నా ప్రాణ దీపమా", "యేసే నా ప్రాణ దీపం",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/07-NA-PRANA-DEEPAM.mp3'),
  Mp3Songs("మొదటి ప్రేమ విడచితివా", "యేసే నా ప్రాణ దీపం",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/08-MODATI-PREMA.mp3'),
  Mp3Songs("ఎగురుతున్న", "యేసే నా ప్రాణ దీపం",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/09-YEGURUCHUNNA.mp3'),

//      8    //

  Mp3Songs("నా జ్యేష్ఠ భాగస్వామి", "నా జ్యేష్ఠ భాగస్వామి",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/02-NAA-JYESTA.mp3'),
  Mp3Songs("నా పరిశుద్ధుడవు", "నా జ్యేష్ఠ భాగస్వామి",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/03-NAA-PARISTHUDHATHA.mp3'),
  Mp3Songs("నిన్ను ఏ మాత్రము", "నా జ్యేష్ఠ భాగస్వామి",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/04-NINU-YE-MATRAMU-FM.mp3'),
  Mp3Songs("మాట్లాడుమయ్య", "నా జ్యేష్ఠ భాగస్వామి",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/05-MATLADU.mp3'),
  Mp3Songs("దేవా జాలి చూపుము", "నా జ్యేష్ఠ భాగస్వామి",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/06-DEVA.mp3'),
  Mp3Songs("దూరమైతివా", "నా జ్యేష్ఠ భాగస్వామి",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/07-DOORAMYTHI.mp3'),
  Mp3Songs("ఎలుగెత్తి పాడనా", "నా జ్యేష్ఠ భాగస్వామి",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/08-YELUGETHI-.mp3'),
  Mp3Songs("శిరము మీద", "నా జ్యేష్ఠ భాగస్వామి",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/09-SIRAMUPY.mp3'),

//      9    //

  Mp3Songs("అందరి ప్రభువైన దేవా", "స్తోత్రార్పణ",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/02-FINAL-Unknown-Artist.mp3'),
  Mp3Songs("నమ్మదగిన దేవుడా నను", "స్తోత్రార్పణ",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/03-FINAL-Unknown-Artist.mp3'),
  Mp3Songs("చెమ్మగిల్లు కళ్ళలోన కన్నీళ్ళెంత", "స్తోత్రార్పణ",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/04-FINAL-Unknown-Artist.mp3'),
  Mp3Songs("జాలరీ ఓ జాలరీ", "స్తోత్రార్పణ",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/05-FINAL-Unknown-Artist-2.mp3'),
  Mp3Songs("యేసు నీ కోసం", "స్తోత్రార్పణ",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/06-YESU-NEEKOSAM-FINAL-Unknown-Artist.mp3'),
  Mp3Songs("వందనాలే నే చేయనా", "స్తోత్రార్పణ",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/07-FINAL-Unknown-Artist-2.mp3'),
  Mp3Songs("కలువరి కొండపైనా", "స్తోత్రార్పణ",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/08-FINAL-Unknown-Artist.mp3'),
  Mp3Songs("పాడవే కోయిలా", "స్తోత్రార్పణ",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/09-FINAL-Unknown-Artist-2.mp3'),

//      10    //

  Mp3Songs("మంచిమనస్సున్న", "మాట తప్పని దేవుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/manchi-manasu.mp3'),
  Mp3Songs("ఎగసిపడే ఆనందం", "మాట తప్పని దేవుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/yegasi-pade-anandham.mp3'),
  Mp3Songs("కృపలను తలపోయుచు", "మాట తప్పని దేవుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/krupalanu-thalapoyuchu.mp3'),
  Mp3Songs("యేసయ్యా నా యేసయ్యా ", "మాట తప్పని దేవుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/yesaiya-na-yesaiya-shalem-raj.mp3'),
  Mp3Songs("యేసూ నీవే నా ఆధారము", "మాట తప్పని దేవుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/yesu-neeve-na.mp3'),
  Mp3Songs("ఎంచితివా దేవా నను", "మాట తప్పని దేవుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/yenchithiva-2.mp3'),
  Mp3Songs("ఇంతకాలము నన్ను కాచెను", "మాట తప్పని దేవుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/intha-kalamu.mp3'),
  Mp3Songs("యేసయ్యా నీ ప్రాణ త్యాగం", "మాట తప్పని దేవుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/yesaiya-ni-prana-hyd.mp3'),

//      11    //

  Mp3Songs("దీవించు మా తండ్రి", "దివించు మా తండ్రి",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/02-Track-2.mp3'),
  Mp3Songs("దీవించు మా తండ్రి", "దివించు మా తండ్రి",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/09-Track-9.mp3'),
  Mp3Songs("నీ ఆశ", "దివించు మా తండ్రి",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/04-Track-4.mp3'),
  Mp3Songs("ప్రేమంటే ప్రేమ", "దివించు మా తండ్రి",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/05-Track-5.mp3'),
  Mp3Songs("సిలువలో నీదు కేక", "దివించు మా తండ్రి",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/06-Track-6.mp3 '),
  Mp3Songs("విన్నపాలు", "దివించు మా తండ్రి",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/vinnapaalu.mp3'),
  Mp3Songs("ఏమివ్వగలనయ్య", "దివించు మా తండ్రి",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/07-Track-7.mp3'),
  Mp3Songs("ఆనంద గానాలు", "దివించు మా తండ్రి",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/10-Track-10.mp3'),

//      12    //

  Mp3Songs("ఎన్నతగని నన్ను!", "మా తండ్రి",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/Maa-Thandri.02-Ennathagani-Nannu.mp3'),
  Mp3Songs("నీ సేవలోనన్ను కరిగిపోని!", "మా తండ్రి",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/Maa-Thandri.03-Nee-Sevalo-Nannu.mp3'),
  Mp3Songs("ఆశ్రయము నీవేనయా", "మా తండ్రి",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/Maa-Thandri.05-Aashrayamu-Neeve.mp3'),
  Mp3Songs("జీవ జలమా!", "మా తండ్రి",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/Maa-Thandri.04-Jeeva-Jalama.mp3'),
  Mp3Songs("అంకితం నీకంకితం!", "మా తండ్రి",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/Maa-Thandri.06-Ankitham.Neekankitham.mp3'),
  Mp3Songs("పరలోక మందున్న మా తండ్రి!", "మా తండ్రి",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/Maa-Thandri.07-Paralokamundunna.mp3'),
  Mp3Songs("మారాలి మారాలి!", "మా తండ్రి",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/Maa-Thandri.08-Maraali-Maraali.mp3'),
  Mp3Songs("యేసూ నీ అనురాగం!", "మా తండ్రి",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/Maa-Thandri.09-Yesu-Nee-Anuragam.mp3'),

//      13    //

  Mp3Songs("ఆశపడకు", "ఆశపడకు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/Track03.mp3'),
  Mp3Songs("ప్రియుడా యేసయ్యా", "ఆశపడకు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/Track05.mp3'),
  Mp3Songs("అందుకొనుము దేవా!", "ఆశపడకు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/Track07.mp3'),
  Mp3Songs("దేవా నా మొర వినవా", "ఆశపడకు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/Track09.mp3'),
  Mp3Songs("కాలం మారినా", "ఆశపడకు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/Track11.mp3'),
  Mp3Songs("ఆనందమానంద", "ఆశపడకు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/Track13.mp3'),
  Mp3Songs("ఉన్నతమందున్న దేవా!", "ఆశపడకు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/Track15.mp3'),
  Mp3Songs("యేసయ్యా నీ ప్రేమకు", "ఆశపడకు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/Track17.mp3'),

//      14    //

  Mp3Songs("ఆరాధనా", "అద్వితీయుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/02-1.mp3'),
  Mp3Songs("ఆకాశమా", "అద్వితీయుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/track02-2.mp3'),
  Mp3Songs("చూచే కన్నులీయుమా", "అద్వితీయుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/05-1.mp3'),
  Mp3Songs("నా ప్రియుడు", "అద్వితీయుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/06-1.mp3'),
  Mp3Songs("గోల్గతా", "అద్వితీయుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/07-1.mp3'),
  Mp3Songs(" నా బలమా ", "అద్వితీయుడు",
      'https://thandrisannidhiministries.org/wp-content/uploads/2023/12/08-1.mp3'),
];
